config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  root 'articles#index'
  resources :tags
  resources :users, only: :show
  resources :articles do
      resources :picks ,only: [:create, :update]
  end
  resources :tag_search, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  # mount_uploader :image, ImagesUploader
  validates :url, presence: true
  has_many :users, through: :user_articles
  has_many :tags, through: :article_tags
  has_many :picks
  has_many :user_articles
  has_many :article_tags

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    # @articles 3 Article.all.order("id DESC").limit(15)

    # articles = Article.al3
    # @articles = articles.order("articles.picks.last.id DESC").limit(15)
    @article = Article.new
    @picks = Pick.all.order("updated_at DESC").uniq(:id).limit(20)
    @articles = Article.all.order("updated_at DESC").uniq(:id).limit(60)
  end

  def show
    @article = Article.find(params[:id])
    @desc_picks = @article.picks.order("id DESC")
    @picks = Pick.all.order("id DESC")
    @tag = Tag.new
    @tags = @article.tags.uniq
    # if current_user.picks.map{|i| [:article_id] == params[:id]}
    # binding.pry
    # if @article.users.ids.include?(current_user.id)
    # if @article.picks.map{|i| i[:user_id].to_i}.include?(current_user.id)
    #   @pick = Pick.where(article_id: params[:id]).where(user_id: current_user.id)[0]
    # else
    #   @pick = Pick.new
    # end
    @pick = Pick.where(article_id: params[:id]).find_or_initialize_by(user_id: current_user.id) if user_signed_in?
  end

  # GET /articles/new
  def new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create

    if params[:article][:url].present?
      article = Article.create(article_params)
      article.picks.create( user_id: current_user.id)
    end
    # respond_to do |format|
    #   if @article.save
    #     format.html { redirect_to @article, notice: 'Article was successfully created.' }
    #     format.json { render :show, status: :created, location: @article }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @article.errors, status: :unprocessable_entity }
    #   end
    # end
    redirect_to root_path
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @article.update(tag_params) if params[:article].present?
    redirect_to @article
    # respond_to do |format|
    #   if @article.update(article_params)
    #   redirect_to @article
    #     format.html { redirect_to @article, notice: 'Article was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @article }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @article.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      # カリキュラム終了後にサービスクラスに移行予定

      agent = Mechanize.new
      page = agent.get(params[:article][:url])
      content = page.at('meta[property="og:description"]')[:content]
      site_name = page.at('meta[property="og:site_name"]')[:content] if page.at('meta[property="og:site_name"]')[:content].present?
      if page.at('meta[property="og:image"]')[:content].present?
        site_image = page.at('meta[property="og:image"]')[:content]
      elsif page.at('meta[name="twitter:image"]')[:content].present?
        site_image = page.at('meta[name="twitter:image"]')[:content]
      else
        site_image = nil
      end
      # カリキュラム終了後にサービスクラスに移行予定
      # params.require(:article).permit(:title, :image, :source)
      params.require(:article).permit(:url).merge(title: page.title,text: content,source: site_name, image: site_image)

    end
    def tag_params
      params.require(:article).permit({tag_ids: []})
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.haml
%li
  .news__box
    .news__box__image-box
      .news__box__image-box__image=render partial: 'image', locals: {image: article.image}
    .news__box__number="#{article.picks.length}Pick"
    =link_to "#{article.title}", "/articles/#{article.id}", class: 'news__box__title'
    .news__box__picker
      -if article.picks.last.user.face.present?
        =link_to render(partial: 'image', locals: {image: article.picks.last.user.face}), "/users/#{article.picks.last.user.id}"
      -else
        =link_to "","/users/#{article.picks.last.user}",class: "image"
      =link_to "#{article.picks.last.user.name}", "/users/#{article.picks.last.user.id}", class: 'news__box__picker__name'
      .news__box__picker__job=article.picks.last.user.company
      .news__box__picker__comment=article.picks.last.comment
    %ul.news__box__pickers.clearfix
      =render partial: 'pickers', collection: article.picks, as: "pick"
      %li.news__box__pickers__face
    .news__box__source=article.source

app/views/articles/_commentbox.haml
.line
.commentbox__unit
  .commnetbox__unit__line.clearfix
    .commentbox__unit__line__face
      =render partial: 'image', locals: { image: pick.user.face}
    .commentbox__unit__line__menu
    .commentbox__unit__line__name= pick.user.name
    .commentbox__unit__line__job= pick.user.company
  .commentbox__unit__comment
    .commentbox__unit__comment__text= pick.comment
    .commentbox__unit__comment__like

app/views/articles/_frame.haml
.header
  .header__menu
    -if user_signed_in?
      =link_to "ログアウト", destroy_user_session_path ,method: :delete
    -else
      =link_to "登録", new_user_registration_path
      =link_to "ログイン", new_user_session_path
  .header__detection
  .header__logo
  .header__user
    .header__user-face
    .header__user-name
    .header__user-style
  .header__info
  .header__pick
-if user_signed_in?
  .menu
    .menu__user
      .menu__user__box
        =link_to image_tag("#{current_user.face}", class: "menu__user__box__face"),"/users/#{current_user.id}"
        .menu__user__box__name=current_user.name
        .menu__user__box__job="#{current_user.company} #{+current_user.position}"
      .menu__user__state.clearfix
        .menu__user__state__following
          %p6 0
          %p フォロー
        .menu__user__state__followed
          %h6 0
          %p フォロワー
      .menu__user__pickstream
        %p タイムライン
    .menu__timeline
      %ul
        =render partial: "pick", collection: @picks

-else
  .menu
    .menu__user
      .menu__user__box
        .menu__user__box__face
        .menu__user__box__name No Account
        .menu__user__box__signup
          =link_to 'アカウントを作成する', new_user_registration_path
      .menu__user__state.clearfix
        .menu__user__state__following
          %p6 -
          %p フォロー
        .menu__user__state__followed
          %h6 -
          %p フォロワー
      .menu__user__pickstream
        %p 人気ユーザー
    .menu__timeline
      %ul
        =render partial: "pick", collection: @picks

app/views/articles/_pick.haml
%li
  =link_to render(partial: 'image', locals: {image: pick.user.face}), "/users/#{pick.user.id}"
  =link_to "#{pick.user.name}","/users/#{pick.user.id}",class: "menu__timeline__name"
  .menu__timeline__picktime 1分
  .menu__timeline__comment=pick.comment
  =link_to "#{pick.article.title}", "/articles/#{pick.article_id}", class: "menu__timeline__link"
  %p をPickしました。
  .line

app/views/articles/_pickers.haml
-if pick.user.face.present?
  =link_to image_tag("#{pick.user.face}", class: 'image'),"/users/#{pick.user.id}"
-else
  =link_to "","/users/#{pick.user.id}",class: 'image'

app/views/articles/_tags.haml
%li
  = link_to tag.name, tag_path(tag.id), class: 'tag'

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
= render partial: "frame"
-if user_signed_in?
  =form_for @article do |f|
    =f.text_field :url, placeholder: "URLを入力", class: 'form'

-if @picks.length > 3
  .contents
    .contents__top
      .contents__top-center
        .contents__top-center__picknumber
        .contents__top-center__title= @picks.first.article.title
        .contents__top-center__source= @picks.first.article.source
        =render partial: 'image', locals: {image: @picks.first.article.image}
      .contents__top-right
        .contents__top-right-top
          .contents__top-right-top__picknumber
          .contents__top-right-top__special 特集
          .contents__top-right-top__title= @picks[1].article.title
          =render partial: 'image', locals: {image: @picks[1].article.image}
        .contents__top-right-bottom
          .contents__top-right-bottom__picknumber
          .contents__top-right-bottom__special 特集
          .contents__top-right-bottom__title= @picks[2].article.title
          =render partial: 'image', locals: {image: @picks[2].article.image}
    .contents__body
      .contents__body__picks

        .contents__body__picks__new-arrival
          .contents__body__picks__new-arrival__headline 新着ニュース
          %ul
            %li
              .contents__body__picks__new-arrival__news
                =link_to '',"http://junk-blog.com/div_a_link/",class: 'contents__body__picks__new-arrival__news-link'
                .contents__body__picks__new-arrival__news__title ゲーマーは要チェック！防塵・防水仕様のゲーミング
                .contents__body__picks__new-arrival__news__source マッシュメディア 224分前
            %li
              .contents__body__picks__new-arrival__news
                =link_to '',"http://junk-blog.com/div_a_link/",class: 'contents__body__picks__new-arrival__news-link'
                .contents__body__picks__new-arrival__news__title イチローは代打で三振　カブス戦
                .contents__body__picks__new-arrival__news__source 共同通信 47NEWS 1時間前
            %li
              .contents__body__picks__new-arrival__news
                =link_to '',"http://junk-blog.com/div_a_link/",class: 'contents__body__picks__new-arrival__news-link'
                .contents__body__picks__new-arrival__news__title 日印原子力協定を承認　NPT未加盟国に原発輸出
                .contents__body__picks__new-arrival__news__source 共同通信 47NEWS 3時間前
            %li
              .contents__body__picks__new-arrival__news
                =link_to '',"http://junk-blog.com/div_a_link/",class: 'contents__body__picks__new-arrival__news-link'
                .contents__body__picks__new-arrival__news__title 福井県知事、もんじゅ廃炉を容認核燃料は県外搬出へ　ほか　12時トップ5ニュース
                .contents__body__picks__new-arrival__news__source マッシュメディア 224分前
            %li
              .contents__body__picks__new-arrival__news
                =link_to '',"http://junk-blog.com/div_a_link/",class: 'contents__body__picks__new-arrival__news-link'
                .contents__body__picks__new-arrival__news__title イチローは代打で三振　カブス戦
                .contents__body__picks__new-arrival__news__source 共同通信 47NEWS 1時間前
            %li
              .contents__body__picks__new-arrival__news
                =link_to '',"http://junk-blog.com/div_a_link/",class: 'contents__body__picks__new-arrival__news-link'
                .contents__body__picks__new-arrival__news__title 日印原子力協定を承認　NPT未加盟国に原発輸出
                .contents__body__picks__new-arrival__news__source 共同通信 47NEWS 3時間前
            %li
              .contents__body__picks__new-arrival__news
                =link_to '',"http://junk-blog.com/div_a_link/",class: 'contents__body__picks__new-arrival__news-link'
                .contents__body__picks__new-arrival__news__title 福井県知事、もんじゅ廃炉を容認核燃料は県外搬出へ　ほか　12時トップ5ニュース
                .contents__body__picks__new-arrival__news__source マッシュメディア 224分前
        %ul
          =render partial: "article", collection: @articles

    / .contents__body__recomend
    /   .contents__body__recomend__tab
    /   .contents__body__recomend__title
    /   .contents__body__recomend__subtitle
    /   .contents__body__recomend__link
    / .contents__body__original
    /   .contents__body__original__line
    /     %h2 NewaPicks オリジナル記事
    /     %h4 NewsPicks オリジナル記事 一覧を見る
    /   .contents__body__original__box
    / .contents__body__feature
    /   .contents__body__feature__line
    /     %h2 特集：新・経営者の条件
    /     %h4 特集：新・経営者の条件 一覧を見る
    /   .contents__body__feature__box
    / .contents__body__inovation
    /   .contents__body__inovation__line
    /     %h2 イノベーション
    /     .logo
    /     %h4 イノベーション 一覧を見る
    /   .contents__body__inovation__box
    / .contents__body__tech
    / .contents__body__business
    / .contents__body__original
    / .contents__body__feature
    / .contents__body__political-economy
    / .contents__body__market
    / .contents__body__education






/     .contents__body__social
/     .contents__body__job
/     .contents__body__good-old
/     .contents__body__analysis
/   .contents__ranking__user
/     .contents__ranking__user__line
/       %h2 ユーザーランキング
/       %h4 ユーザーランキング 一覧を見る
/     .contents__ranking__user__box
/       .number
/       .contents__ranking__user__box__face
/       .contents__ranking__user__box__info
/         .contents__ranking__user__box__info__name
/         .contents__ranking__user__box__info__tag
/         .contents__ranking__user__box__info__job
/         .contents__ranking__user__box__info__like_number
/       .contents__ranking__user__box___follow-tag
/   .contents__ranking__comment
/     .contents__ranking__comment__line
/       %h2 コメントランキング
/       %h4 コメントランキング 一覧を見る。
/     .contents__ranking__comment__box
/       .contents__ranking__comment__box__user
/         .contents__ranking__comment__box__number
/         .contents__ranking__comment__box__face
/         .contents__ranking__comment__box__name
/         .contents__ranking__comment__box__job
/         .contents__ranking__comment__box__likes
/         .comments__ranking__comment__box__tag
/       .contents__ranking__comment__box__comment
/       .contents__ranking__comment__box__source
/         .contents__ranking__comment__box__source__title
/         .contents__ranking__comment__box__source__publisher
/ .footer
/   .footer__line
/   .footer__tag

app/views/articles/new.html.haml
.header
  .header__menu hoge
  .header__detection
  .header__logo
  .header__signup
  .header__login
.user__menu
.header__line
.contents
  .contents__body
    .contents__body__news
    .contents__body__comments
  .contents__infoz
  .contents__ranking__comment
.comment-line

app/views/articles/show.html.haml
= render partial: "frame"
.contents
  .contents__back
    =link_to "←総合トップ", root_path, class: 'contents__back__root'
  .contents__news
    .contents__news__picks.clearfix
      .contents__news__picks-left
        .contents__news__picks-left-top
          -if @article.image.present?
            .contents__news__picks-left-top-top
              =image_tag("#{@article.image}", class: "contents__news__picks-left-top-top__image")
          .contents__news__picks-left-top__number= "#{@article.picks.length} Picks"
          .contents__news__picks-left-top__title= @article.title
          .contents__news__picks-left-top__source= @article.source
          .contents__news__picks-left-top__text= @article.text
          =link_to '続きを読む', "#{@article.url}",class: 'contents__news__picks-left-top__link'
        .contents__news__picks-left-bottom
          .contents__news__picks-left-bottom__pickbox.clearfix
            =image_tag("#{current_user.face}", class: "contents__news__picks-left-bottom__pickbox__face") if user_signed_in?
            -if user_signed_in?
              =form_for [@article,@pick] do |f|
                =f.text_field :comment, placeholder: "コメントを書く(任意)",class: 'contents__news__picks-left-bottom__pickbox__comment'
                .contents__news__picks-left-bottom__pickbox__share シェアする
                =f.submit "Pick",class: 'contents__news__picks-left-bottom__pickbox__pick'
          .contents__news__picks-left-bottom__commentbox
            %p 選択しているユーザー
            .line
            .commentbox__unit
              .commnetbox__unit__line.clearfix
                = render partial: 'commentbox' ,collection: @desc_picks ,as: "pick"
            .line
            %p フォローしているユーザーのコメント
            .line
            .contents__news__picks-left-bottom__commentbox__unit
              .contents__news__picks-left-bottom__commentbox__unit__face
              .contents__news__picks-left-bottom__commentbox__unit__name
              .contents__news__picks-left-bottom__commentbox__unit__job
              .contents__news__picks-left-bottom__commentbox__unit__comment
              .contents__news__picks-left-bottom__commentbox__unit__like
          .contents__news__picks-left-bottom__commentbox
            %p おすすめのユーザーのコメント
            .contents__news__picks-left-bottom__commentbox__unit
              .contents__news__picks-left-bottom__commentbox__unit__face

              .contents__news__picks-left-bottom__commentbox__unit__name
              .contents__news__picks-left-bottom__commentbox__unit__job
              .contents__news__picks-left-bottom__commentbox__unit__comment
              .contents__news__picks-left-bottom__commentbox__unit__like


      .contents__news__picks-tags
        .contents__news__picks-tags__input.clearfix
          %p タグを更新する
          =form_for(@article) do |f|
            =text_field :tag, :name, placeholder: "タグを検索します", autocomplete: "off", class: 'text_field'

            %ul.tag_search
            / = collection_check_boxes(:article, :tag_ids, Tag.all, :id, :name)

            / =hidden_field :article_id, params[:id]
            .line
            %p 選択されたタグ
            %ul.add_tag_list
            .line
            =f.submit "タグ付けする", class: 'button'
        .contents__news__picks-tags__create
          %p 新しいタグを作り、タグ付けする
          =form_for(@tag) do |f|
            =f.text_field :name, class: 'tag_field'
            =f.submit "タグを作る", class: 'button'
            =hidden_field_tag 'article_id', params[:id]
        .contents__news__picks-tags__added
          %p この記事のタグ
          %ol
            =render partial: "tags",collection: @tags, as: "tag"

/     .contents__body__news
/     .contents__body__comments
/   .contents__info
/   .contents__ranking__comment
/ .comment-line