config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  root 'articles#index'
  resources :tags
  resources :users, only: :show
  resources :articles do
      resources :picks ,only: [:create, :update]
  end
  resources :tag_search, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord

  validates :name, uniqueness: true, presence: true
  has_many :users
  has_many :articles, through: :article_tags
  has_many :article_tags

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])
    @articles = @tag.articles.uniq
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @article = Article.find(params[:article_id])
    @tag = @article.tags.create(tag_params)
    redirect_to @article
    # respond_to do |format|
    #   if @tag.save
    #     format.html { redirect_to @article, notice: 'Tag was successfully created.' }
    #     format.json { render :show, status: :created, location: @tag }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @tag.errors, status: :unprocessable_entity }
      # end
    # end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :text)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_article.haml
%li
  .news__box
    .news__box__image-box
      .news__box__image-box__image=render partial: 'image', locals: {image: article.image}
    .news__box__number="#{article.picks.length}Pick"
    =link_to "#{article.title}", "/articles/#{article.id}", class: 'news__box__title'
    .news__box__picker
      -if article.picks.last.user.face.present?
        =link_to render(partial: 'image', locals: {image: article.picks.last.user.face}), "/users/#{article.picks.last.user.id}"
      -else
        =link_to "","/users/#{article.picks.last.user}",class: "image"
      =link_to "#{article.picks.last.user.name}", "/users/#{article.picks.last.user.id}", class: 'news__box__picker__name'
      .news__box__picker__job=article.picks.last.user.company
      .news__box__picker__comment=article.picks.last.comment
    %ul.news__box__pickers.clearfix
      =link_to render(partial: 'pickers', collection: article.picks, as: "pick"), "/users/#{article.picks.last.user.id}"
      %li.news__box__pickers__face
    .news__box__source=article.source

app/views/tags/_form.html.haml
= form_for @tag do |f|
  - if @tag.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
      %ul
        - @tag.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :text
    = f.text_field :text
  .actions
    = f.submit 'Save'

app/views/tags/_image.haml
-if image.present?
  = image_tag("#{image}", class: 'image')
-else
  .image

app/views/tags/_pickers.haml
-if pick.user.face.present?
  =image_tag("#{pick.user.face}", class: 'image')
-else
  .image

app/views/tags/edit.html.haml
%h1 Editing tag

= render 'form'

= link_to 'Show', @tag
\|
= link_to 'Back', tags_path

app/views/tags/index.html.haml
%h1 Listing tags

%table
  %thead
    %tr
      %th Name
      %th Text
      %th
      %th
      %th

  %tbody
    - @tags.each do |tag|
      %tr
        %td= tag.name
        %td= tag.text
        %td= link_to 'Show', tag
        %td= link_to 'Edit', edit_tag_path(tag)
        %td= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Tag', new_tag_path

app/views/tags/new.html.haml
%h1 New tag

= render 'form'

= link_to 'Back', tags_path

app/views/tags/show.html.haml
.header

.tags__content
  %p#notice= notice
  %p
    %b タグ：
    = @tag.name
    = link_to 'Edit', edit_tag_path(@tag)
    \|
    = link_to 'Back', tags_path

.tags__articles
  %ul
    =render partial: "article", collection: @articles, as: "article"