config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  root 'articles#index'
  resources :tags
  resources :users, only: :show
  resources :articles do
      resources :picks ,only: [:create, :update]
  end
  resources :tag_search, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pick.rb
class Pick < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  before_action :set_pick, only: [:show, :edit, :update, :destroy]

  # GET /picks
  # GET /picks.json
  def index
    @picks = Pick.all
  end

  # GET /picks/1
  # GET /picks/1.json
  def show
  end

  # GET /picks/new
  def new
    @pick = Pick.new
  end

  # GET /picks/1/edit
  def edit
  end

  # POST /picks
  # POST /picks.json
  def create
    Pick.create(pick_params)
    redirect_to article_path(params[:article_id])

    # respond_to do |format|
    #   if @pick.save
    #     format.html { redirect_to @pick, notice: 'Pick was successfully created.' }
    #     format.json { render :show, status: :created, location: @pick }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @pick.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /picks/1
  # PATCH/PUT /picks/1.json
  def update
    @pick.update(pick_params)
    redirect_to article_path(params[:article_id])
    # respond_to do |format|
    #   if @pick.update(pick_params)
    #     format.html { redirect_to @pick, notice: 'Pick was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @pick }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @pick.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /picks/1
  # DELETE /picks/1.json
  def destroy
    @pick.destroy
    respond_to do |format|
      format.html { redirect_to picks_url, notice: 'Pick was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pick
      @pick = Pick.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pick_params
      params.require(:pick).permit(:comment).merge(user_id: current_user.id, article_id: params[:article_id])
    end
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/views/picks/edit.html.haml
%h1 Editing pick

= render 'form'

= link_to 'Show', @pick
\|
= link_to 'Back', picks_path

app/views/picks/index.html.haml
%h1 Listing picks

%table
  %thead
    %tr
      %th User
      %th Article
      %th
      %th
      %th

  %tbody
    - @picks.each do |pick|
      %tr
        %td= pick.user_id
        %td= pick.article_id
        %td= link_to 'Show', pick
        %td= link_to 'Edit', edit_pick_path(pick)
        %td= link_to 'Destroy', pick, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Pick', new_pick_path

app/views/picks/new.html.haml
%h1 New pick

= render 'form'

= link_to 'Back', picks_path

app/views/picks/show.html.haml
%p#notice= notice

%p
  %b User:
  = @pick.user_id
%p
  %b Article:
  = @pick.article_id

= link_to 'Edit', edit_pick_path(@pick)
\|
= link_to 'Back', picks_path